version: '3.4'

networks:
  k6:
  grafana:

services:
  prometheus:
    image: prom/prometheus
#    entrypoint: /bin/sh
#    user: root    
    networks:
      - k6
      - grafana
    ports:
      - 9090:9090
    command:
      - --web.enable-remote-write-receiver
      - --enable-feature=native-histograms
      - --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:8.5.21
#    entrypoint: /bin/sh
#    user: root
    networks:
      - grafana
    ports:
      - "23000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_USERS_ALLOW_SIGN_UP=false
        #      - GF_AUTH_DISABLE_LOGIN_FORM=true
        #      - GF_AUTH_DISABLE_SIGNOUT_MENU=true
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_LOG_FILTERS=rendering:debug
    volumes:
      - ./grafana-dashboard:/dashboard
        #      - ./dashboards:/var/lib/grafana/dashboards
      - ./grafana-provisioning:/etc/grafana/provisioning
      - ./grafana-dashboard:/var/lib/grafana/dashboards
        #      - ./grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
        #      - ./grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

  renderer:
    image: grafana/grafana-image-renderer:latest
#    entrypoint: /bin/sh
#    user: root
    networks:
      - grafana
    ports:
      - "8081:8081"
    depends_on:
      - grafana

  k6:
    image: grafana/k6:latest
#    image: loadimpact/k6:latest
#    entrypoint: /bin/sh
#    user: root
    networks:
      - k6
    ports:
      - "6565:6565"
    environment:
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
      - K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM=true
    volumes:
      - ./scripts:/scripts
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - prometheus


  reporter:
    image: izakmarais/grafana-reporter:${gr_version:-latest}
    command: "-ip grafana:3000"
    networks:
      - grafana
    ports:
      - "8686:8686"
    depends_on:
      - grafana
